import { GoogleGenAI, Modality, Type } from "@google/genai";

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable is not set.");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const base64ToGenerativePart = (base64Data: string, mimeType: string) => {
  return {
    inlineData: {
      data: base64Data.split(',')[1],
      mimeType,
    },
  };
};

export const generateAdMockup = async (
  productImageBase64: string,
  productImageMimeType: string,
  background: { type: 'scene', value: string } | { type: 'custom', image: string, mimeType: string },
  channel: string,
  adText: string,
  placementInstructions: string,
): Promise<string> => {
  const model = 'gemini-2.5-flash-image-preview';
  
  const parts = [];
  let textPrompt = '';

  const productPart = base64ToGenerativePart(productImageBase64, productImageMimeType);
  parts.push(productPart);

  if (background.type === 'custom') {
    const backgroundPart = base64ToGenerativePart(background.image, background.mimeType);
    parts.push(backgroundPart);
    textPrompt = `
      You are an expert social media ad designer.
      Task: Create a compelling ad mockup by combining the two provided images.
      1.  **Image 1:** This is the product image.
      2.  **Image 2:** This is the background image.
      3.  **Placement:** Place the product from Image 1 onto the background (Image 2). ${placementInstructions ? `Follow these placement instructions carefully: "${placementInstructions}".` : ''} The product should look naturally blended with realistic lighting and shadows. Make sure the scale and perspective are correct.
      4.  **Platform Optimization:** Style the final image as a professional social media ad for '${channel}'. Pay attention to typical aspect ratios, aesthetics, and compositions that perform well on this platform (e.g., for TikTok, use a 9:16 vertical format; for Instagram feed, use 1:1 or 4:5).
      5.  **Text Overlay:** ${adText ? `Incorporate the text "${adText}" onto the image. The text should be clear, stylish, and legible, using a font and placement suitable for a high-converting advertisement.` : 'Do not add any text.'}
      6.  **Final Output:** The result must be a single, complete image. Do not describe what you did; only output the final ad image.
    `;
  } else { // background.type === 'scene'
    textPrompt = `
      You are an expert social media ad designer.
      Task: Create a compelling ad mockup.
      1.  **Product Integration:** Take the product from the provided image and seamlessly integrate it into a high-quality, realistic '${background.value}' scene. ${placementInstructions ? `Follow these placement instructions carefully: "${placementInstructions}".` : ''} The product should be the clear focus, with realistic lighting and shadows.
      2.  **Platform Optimization:** Style the final image as a professional social media ad for '${channel}'. Pay attention to typical aspect ratios, aesthetics, and compositions that perform well on this platform (e.g., for TikTok, use a 9:16 vertical format; for Instagram feed, use 1:1 or 4:5).
      3.  **Text Overlay:** ${adText ? `Incorporate the text "${adText}" onto the image. The text should be clear, stylish, and legible, using a font and placement suitable for a high-converting advertisement.` : 'Do not add any text.'}
      4.  **Final Output:** The result must be a single, complete image. Do not describe what you did; only output the final ad image.
    `;
  }

  parts.push({ text: textPrompt });
  
  const response = await ai.models.generateContent({
    model: model,
    contents: {
      parts: parts,
    },
    config: {
        responseModalities: [Modality.IMAGE, Modality.TEXT],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      const base64ImageBytes: string = part.inlineData.data;
      const mimeType = part.inlineData.mimeType;
      return `data:${mimeType};base64,${base64ImageBytes}`;
    }
  }

  throw new Error('No image was generated by the model.');
};


export const generateAdCopy = async (
  channel: string,
  productType: string,
  productDetails: string,
  tone: string,
): Promise<string[]> => {
  const model = 'gemini-2.5-flash';
  const prompt = `
    You are an expert social media copywriter.
    Your task is to generate 2-3 short, engaging ad captions for a product.

    - **Social Media Channel:** ${channel}
    - **Product Type:** ${productType}
    - **Product Details:** ${productDetails}
    - **Desired Tone:** ${tone}

    **Requirements:**
    1.  **Tailor to the Channel:** The captions must be formatted natively for ${channel}.
        - For Instagram/X: Use relevant hashtags.
        - For TikTok: Use a casual, trending-sound-friendly style.
        - For LinkedIn: Use a professional and benefit-driven tone.
        - For Facebook: Use a clear and direct approach.
    2.  **Match the Tone:** The writing style must be ${tone}.
    3.  **Short & Punchy:** Each caption must be under 50 words.
    4.  **Strong Call to Action (CTA):** Each caption must end with a clear CTA (e.g., "Shop now," "Learn more," "Link in bio!").
    5.  **Output Format:** Return a JSON object with a single key "captions", which is an array of 2-3 of the generated caption strings.
  `;

  const response = await ai.models.generateContent({
    model: model,
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          captions: {
            type: Type.ARRAY,
            items: {
              type: Type.STRING,
              description: 'A single ad caption under 50 words.'
            }
          }
        }
      }
    }
  });
  
  const jsonStr = response.text.trim();
  const result = JSON.parse(jsonStr);

  if (result && result.captions && Array.isArray(result.captions)) {
    return result.captions;
  }

  throw new Error('Failed to parse valid captions from the model response.');
};